project:
  type: website

metadata-files: 
  - _sidebar.yml

html-table-processing: none

website: 
  title: gt-extras
  description: "A Collection of Helper Functions for the Great-Tables Package."
  site-url: https://posit-dev.github.io/gt-extras/
  page-navigation: true
  navbar:
    left:
      - text: Get Started
        file: get-started/index.qmd
      - reference/index.qmd


quartodoc:
  package: gt_extras
  dir: reference
  title: API Reference
  css: reference/_styles-quartodoc.css

  # write sidebar data
  sidebar: _sidebar.yml
  #css: reference/_styles-quartodoc.css

  sections:
    - title: Themes
      desc: Functions to generate themes.
      contents:
        - gt_theme_538
        - gt_theme_espn
        - gt_theme_guardian
        - gt_theme_nytimes
        - gt_theme_excel
        - gt_theme_dot_matrix
        - gt_theme_dark
        - gt_theme_pff

    - title: Colors
      desc: "" # TODO: add desc
      contents:
        - gt_highlight_cols
        - gt_hulk_col_numeric
    
    - title: Icons and Images
      desc: "" # TODO: add desc
      contents:
        - fa_icon_repeat


format:
  html:
    theme:
      light: simplex
      # dark: superhero
    respect-user-color-scheme: true
    css:
      - styles.css
      - reference/_styles-quartodoc.css
    toc: true
    page-layout: full